# Form implementation generated from reading ui file 'boletas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(818, 703)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 150, 181, 16))
        self.label_10.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:10pt;\n"
"color: #9d9d9d;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(360, 70, 291, 51))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:20pt;\n"
"color: #8B4513\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 201, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/Logo2.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_superior = QtWidgets.QFrame(parent=Dialog)
        self.frame_superior.setGeometry(QtCore.QRect(30, 0, 791, 42))
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_superior)
        self.label_9.setStyleSheet("font: 900 10pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(565, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setStyleSheet("")
        self.bt_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/window-minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon1)
        self.bt_restaurar.setIconSize(QtCore.QSize(28, 28))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(28, 28))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar_2 = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar_2.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar_2.setStyleSheet("")
        self.bt_cerrar_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar_2.setIcon(icon3)
        self.bt_cerrar_2.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar_2.setObjectName("bt_cerrar_2")
        self.horizontalLayout.addWidget(self.bt_cerrar_2)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 170, 881, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 141, 16))
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_nombre = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_nombre.setGeometry(QtCore.QRect(130, 200, 241, 31))
        self.lineEdit_nombre.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_nombre.setText("")
        self.lineEdit_nombre.setObjectName("lineEdit_nombre")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 280, 81, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.lineEdit_nombre_4 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_nombre_4.setGeometry(QtCore.QRect(130, 270, 241, 31))
        self.lineEdit_nombre_4.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_nombre_4.setText("")
        self.lineEdit_nombre_4.setObjectName("lineEdit_nombre_4")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 340, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(470, 190, 91, 16))
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(570, 190, 161, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        self.label_11.setGeometry(QtCore.QRect(430, 240, 181, 16))
        self.label_11.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:13pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.dateEdit_Devolucion = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit_Devolucion.setGeometry(QtCore.QRect(630, 230, 110, 31))
        self.dateEdit_Devolucion.setCalendarPopup(True)
        self.dateEdit_Devolucion.setObjectName("dateEdit_Devolucion")
        self.label_12 = QtWidgets.QLabel(parent=Dialog)
        self.label_12.setGeometry(QtCore.QRect(540, 280, 111, 16))
        self.label_12.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit_nombre_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_nombre_2.setGeometry(QtCore.QRect(490, 310, 241, 31))
        self.lineEdit_nombre_2.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_nombre_2.setText("")
        self.lineEdit_nombre_2.setObjectName("lineEdit_nombre_2")
        self.label_13 = QtWidgets.QLabel(parent=Dialog)
        self.label_13.setGeometry(QtCore.QRect(540, 360, 141, 16))
        self.label_13.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(523, 390, 161, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 430, 481, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton_registrar = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_registrar.setGeometry(QtCore.QRect(540, 530, 191, 41))
        self.pushButton_registrar.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"font: 700 15pt \"Segoe UI\";\n"
"color: #8B4513;")
        self.pushButton_registrar.setObjectName("pushButton_registrar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "Rellena los siguientes campos"))
        self.label_2.setText(_translate("Dialog", "Generacion De Boletas"))
        self.label_9.setText(_translate("Dialog", "Registro de Calificacion"))
        self.label_4.setText(_translate("Dialog", "Nombre"))
        self.label_5.setText(_translate("Dialog", "Apellido"))
        self.label_6.setText(_translate("Dialog", "ID"))
        self.label_8.setText(_translate("Dialog", "Asistencia"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "---Seleccione una opcion"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Aprovado"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "No Aprovado"))
        self.label_11.setText(_translate("Dialog", "Fecha De Evaluación"))
        self.label_12.setText(_translate("Dialog", "% Asistencia"))
        self.label_13.setText(_translate("Dialog", "Promedio Final"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Asignaturas"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "1ER Grado"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "2DO Grado"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "3ER Grado"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Promedio"))
        self.pushButton_registrar.setText(_translate("Dialog", "Exportar PDF"))
