# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color:#8c8c8c;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_superior)
        self.label.setStyleSheet("font: 900 10pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(565, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setStyleSheet("")
        self.bt_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/window-minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon1)
        self.bt_restaurar.setIconSize(QtCore.QSize(28, 28))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(28, 28))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar_2 = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar_2.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar_2.setStyleSheet("")
        self.bt_cerrar_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar_2.setIcon(icon3)
        self.bt_cerrar_2.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar_2.setObjectName("bt_cerrar_2")
        self.horizontalLayout.addWidget(self.bt_cerrar_2)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: #9a9a9a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    color: rgb(20, 200, 220);\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(53,53,79);\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_uno = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_uno.setAutoFillBackground(False)
        self.bt_uno.setStyleSheet("\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/user-plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_uno.setIcon(icon4)
        self.bt_uno.setIconSize(QtCore.QSize(32, 32))
        self.bt_uno.setObjectName("bt_uno")
        self.verticalLayout_4.addWidget(self.bt_uno)
        self.bt_dos = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_dos.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/book (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_dos.setIcon(icon5)
        self.bt_dos.setIconSize(QtCore.QSize(32, 32))
        self.bt_dos.setObjectName("bt_dos")
        self.verticalLayout_4.addWidget(self.bt_dos)
        self.bt_tres = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_tres.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/dollar-sign.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_tres.setIcon(icon6)
        self.bt_tres.setIconSize(QtCore.QSize(32, 32))
        self.bt_tres.setObjectName("bt_tres")
        self.verticalLayout_4.addWidget(self.bt_tres)
        self.bt_cuatro = QtWidgets.QPushButton(parent=self.frame_2)
        self.bt_cuatro.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/archive.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cuatro.setIcon(icon7)
        self.bt_cuatro.setIconSize(QtCore.QSize(32, 32))
        self.bt_cuatro.setObjectName("bt_cuatro")
        self.verticalLayout_4.addWidget(self.bt_cuatro)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setStyleSheet("QFrame {\n"
"    background-color: #9a9a9a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    color: rgb(20, 200, 220);\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setStyleSheet("QFrame {\n"
"    background-color: #9a9a9a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    color: rgb(20, 200, 220);\n"
"    border-radius: 5px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(53,53,79);\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_menu_uno = QtWidgets.QPushButton(parent=self.frame_6)
        self.bt_menu_uno.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/arrow-narrow-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_uno.setIcon(icon8)
        self.bt_menu_uno.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_uno.setObjectName("bt_menu_uno")
        self.horizontalLayout_3.addWidget(self.bt_menu_uno)
        self.bt_menu_dos = QtWidgets.QPushButton(parent=self.frame_6)
        self.bt_menu_dos.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Icons/arrow-narrow-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_menu_dos.setIcon(icon9)
        self.bt_menu_dos.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_dos.setObjectName("bt_menu_dos")
        self.horizontalLayout_3.addWidget(self.bt_menu_dos)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_6)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"border: 2px solid #14c8dc;\n"
"border-radius: 8px;\n"
"color: #ffffff;\n"
"background-color: rgb(0,0,0);\n"
"font: 75 12pt \"Times New Roman\";\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_11.setStyleSheet("QFrame {\n"
"    background-color: #9a9a9a;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font: 87 12pt \"Arial Black\";\n"
"    background-color: #000000ff;\n"
"    color: rgb(20, 200, 220);\n"
"    border-radius: 5px;\n"
"    border:0px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: black;\n"
"}\n"
"")
        self.pushButton_11.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Icons/zoom.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon10)
        self.pushButton_11.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox = QtWidgets.QToolBox(parent=self.frame_7)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 Spt \'MS Shell Dlg 2\';\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(20, 200, 220);\n"
"    font: 75 12pt \'MS Shell Dlg 2\';\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 274, 364))
        self.page.setObjectName("page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_11.addWidget(self.pushButton)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Icons/app-window.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolBox.addItem(self.page, icon11, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        self.toolBox.addItem(self.page_5, icon11, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 274, 364))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_13.addWidget(self.pushButton_3)
        self.toolBox.addItem(self.page_2, icon11, "")
        self.verticalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_paginas.setStyleSheet("\n"
"QFrame{\n"
"background-color:#9a9a9a;\n"
"}\n"
"\n"
"QLabel{\n"
"font: 87 12pt *Arial Black*;\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border:0px solid #14C8DC\n"
"}\n"
"\n"
"")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stackedWidget.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_uno = QtWidgets.QWidget()
        self.page_uno.setObjectName("page_uno")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_uno)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.page_uno)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Icons/user-plus.svg"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page_uno)
        self.page_dos = QtWidgets.QWidget()
        self.page_dos.setObjectName("page_dos")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_dos)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(parent=self.page_dos)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Icons/book (1).svg"))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_dos)
        self.page_tres = QtWidgets.QWidget()
        self.page_tres.setObjectName("page_tres")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_tres)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(parent=self.page_tres)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Icons/dollar-sign.svg"))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_tres)
        self.page_cuatro = QtWidgets.QWidget()
        self.page_cuatro.setObjectName("page_cuatro")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_cuatro)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.page_cuatro)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Icons/archive.svg"))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.page_cuatro)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Menu"))
        self.bt_uno.setText(_translate("MainWindow", "   Registrar Usuario"))
        self.bt_dos.setText(_translate("MainWindow", "  Registrar Material"))
        self.bt_tres.setText(_translate("MainWindow", "Prestamos/Devoluciones"))
        self.bt_cuatro.setText(_translate("MainWindow", "  Reportes"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "pagina uno"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "pagina dos"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "pagina tres"))
