# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 240, 49, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(160, 230, 241, 41))
        self.lineEdit.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 310, 241, 41))
        self.lineEdit_2.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 310, 101, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 390, 121, 24))
        self.pushButton.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"font: 700 11pt \"Segoe UI\";\n"
"color: #8B4513;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 20, 361, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/Logo2.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Email "))
        self.label_3.setText(_translate("Dialog", "Contraseña"))
        self.pushButton.setText(_translate("Dialog", "Entrar"))
