# Form implementation generated from reading ui file 'registroMaterial.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(881, 651)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setGeometry(QtCore.QRect(50, 200, 181, 16))
        self.label_10.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:10pt;\n"
"color: #9d9d9d;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 181, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 220, 881, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 321, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/Logo2.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(440, 120, 321, 51))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:25pt;\n"
"color: #8B4513\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.frame_superior = QtWidgets.QFrame(parent=Dialog)
        self.frame_superior.setGeometry(QtCore.QRect(0, 0, 881, 42))
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_superior)
        self.label_9.setStyleSheet("font: 900 10pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(565, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setStyleSheet("")
        self.bt_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/window-minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon1)
        self.bt_restaurar.setIconSize(QtCore.QSize(28, 28))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(28, 28))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar_2 = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar_2.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar_2.setStyleSheet("")
        self.bt_cerrar_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar_2.setIcon(icon3)
        self.bt_cerrar_2.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar_2.setObjectName("bt_cerrar_2")
        self.horizontalLayout.addWidget(self.bt_cerrar_2)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(650, 250, 171, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.comboBox_Material = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Material.setGeometry(QtCore.QRect(0, 430, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Material.setFont(font)
        self.comboBox_Material.setObjectName("comboBox_Material")
        self.comboBox_Material.addItem("")
        self.comboBox_Material.addItem("")
        self.comboBox_Material.addItem("")
        self.comboBox_Material.addItem("")
        self.comboBox_Material.addItem("")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(640, 380, 141, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 380, 151, 16))
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_registrar_Libros = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_registrar_Libros.setGeometry(QtCore.QRect(330, 530, 191, 41))
        self.pushButton_registrar_Libros.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"font: 700 15pt \"Segoe UI\";\n"
"color: #8B4513;")
        self.pushButton_registrar_Libros.setObjectName("pushButton_registrar_Libros")
        self.comboBox_area = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_area.setGeometry(QtCore.QRect(647, 430, 171, 22))
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.lineEdit_Titulo_Materia = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Titulo_Materia.setGeometry(QtCore.QRect(20, 300, 241, 31))
        self.lineEdit_Titulo_Materia.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_Titulo_Materia.setText("")
        self.lineEdit_Titulo_Materia.setObjectName("lineEdit_Titulo_Materia")
        self.comboBox_Profesor = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Profesor.setGeometry(QtCore.QRect(640, 300, 181, 22))
        self.comboBox_Profesor.setObjectName("comboBox_Profesor")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(330, 270, 191, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Icons/buho.svg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "Rellena los siguientes campos"))
        self.label_3.setText(_translate("Dialog", "Nombre De Materia"))
        self.label_2.setText(_translate("Dialog", "Registro De Materias"))
        self.label_9.setText(_translate("Dialog", "Registro de Materia"))
        self.label_5.setText(_translate("Dialog", "Profesor a Impartir"))
        self.comboBox_Material.setItemText(0, _translate("Dialog", "--- Seleccione una opción"))
        self.comboBox_Material.setItemText(1, _translate("Dialog", "Libros"))
        self.comboBox_Material.setItemText(2, _translate("Dialog", "Libretas"))
        self.comboBox_Material.setItemText(3, _translate("Dialog", "Utiles Basicos"))
        self.comboBox_Material.setItemText(4, _translate("Dialog", "Atencion Especial"))
        self.label_7.setText(_translate("Dialog", "Area Academica"))
        self.label_8.setText(_translate("Dialog", "Tipo de material"))
        self.pushButton_registrar_Libros.setText(_translate("Dialog", "Registrar"))
        self.comboBox_area.setItemText(0, _translate("Dialog", "CienciasBasicas"))
        self.comboBox_area.setItemText(1, _translate("Dialog", "Literatura"))
        self.comboBox_area.setItemText(2, _translate("Dialog", "Arte"))
