# Form implementation generated from reading ui file 'prestamosDevolucion.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(795, 781)
        self.frame_superior = QtWidgets.QFrame(parent=Dialog)
        self.frame_superior.setGeometry(QtCore.QRect(0, 0, 791, 42))
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:20px\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_superior)
        self.label_9.setStyleSheet("font: 900 10pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(565, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_minimizar.setIcon(icon)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_restaurar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_restaurar.setStyleSheet("")
        self.bt_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/window-minimize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_restaurar.setIcon(icon1)
        self.bt_restaurar.setIconSize(QtCore.QSize(28, 28))
        self.bt_restaurar.setObjectName("bt_restaurar")
        self.horizontalLayout.addWidget(self.bt_restaurar)
        self.bt_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/maximize.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(28, 28))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar_2 = QtWidgets.QPushButton(parent=self.frame_superior)
        self.bt_cerrar_2.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar_2.setStyleSheet("")
        self.bt_cerrar_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_cerrar_2.setIcon(icon3)
        self.bt_cerrar_2.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar_2.setObjectName("bt_cerrar_2")
        self.horizontalLayout.addWidget(self.bt_cerrar_2)
        self.lineEdit_Segundo_Apellido = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Segundo_Apellido.setGeometry(QtCore.QRect(80, 510, 241, 31))
        self.lineEdit_Segundo_Apellido.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_Segundo_Apellido.setText("")
        self.lineEdit_Segundo_Apellido.setObjectName("lineEdit_Segundo_Apellido")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(-20, 30, 341, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/Logo.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_IdLibro = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_IdLibro.setGeometry(QtCore.QRect(430, 280, 241, 31))
        self.lineEdit_IdLibro.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_IdLibro.setText("")
        self.lineEdit_IdLibro.setObjectName("lineEdit_IdLibro")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(-30, 210, 881, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(410, 110, 371, 51))
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:25pt;\n"
"color: #8B4513\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(130, 350, 141, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(120, 470, 171, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(parent=Dialog)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 181, 16))
        self.label_10.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:10pt;\n"
"color: #9d9d9d;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 250, 141, 16))
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 240, 141, 16))
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.pushButton_registrar_Libros = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_registrar_Libros.setGeometry(QtCore.QRect(300, 640, 191, 41))
        self.pushButton_registrar_Libros.setStyleSheet("background-color: rgb(181, 181, 181);\n"
"font: 700 15pt \"Segoe UI\";\n"
"color: #8B4513;")
        self.pushButton_registrar_Libros.setObjectName("pushButton_registrar_Libros")
        self.lineEdit_Nombre = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Nombre.setGeometry(QtCore.QRect(70, 400, 241, 31))
        self.lineEdit_Nombre.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_Nombre.setText("")
        self.lineEdit_Nombre.setObjectName("lineEdit_Nombre")
        self.comboBox_Libro = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_Libro.setGeometry(QtCore.QRect(90, 290, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Libro.setFont(font)
        self.comboBox_Libro.setObjectName("comboBox_Libro")
        self.comboBox_Libro.addItem("")
        self.comboBox_Libro.addItem("")
        self.comboBox_Libro.addItem("")
        self.comboBox_Libro.addItem("")
        self.comboBox_Libro.addItem("")
        self.lineEdit_Apellido = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_Apellido.setGeometry(QtCore.QRect(450, 390, 241, 31))
        self.lineEdit_Apellido.setStyleSheet("font-size:14pt; \n"
"color: rgb(202, 202, 202); ")
        self.lineEdit_Apellido.setText("")
        self.lineEdit_Apellido.setObjectName("lineEdit_Apellido")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(480, 350, 141, 16))
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:15pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(410, 470, 141, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:10pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        self.label_11.setGeometry(QtCore.QRect(560, 470, 141, 16))
        self.label_11.setStyleSheet("QLabel{\n"
"color: rgb(218, 218, 218); font-size:10pt;\n"
"color: #8B4513;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.dateEdit_Prestamo = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit_Prestamo.setGeometry(QtCore.QRect(410, 510, 110, 31))
        self.dateEdit_Prestamo.setCalendarPopup(True)
        self.dateEdit_Prestamo.setObjectName("dateEdit_Prestamo")
        self.dateEdit_Devolucion = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit_Devolucion.setGeometry(QtCore.QRect(570, 510, 110, 31))
        self.dateEdit_Devolucion.setCalendarPopup(True)
        self.dateEdit_Devolucion.setObjectName("dateEdit_Devolucion")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "Registro de Usuario"))
        self.label_2.setText(_translate("Dialog", "Prestamos/Devoluciones"))
        self.label_7.setText(_translate("Dialog", "Nombre"))
        self.label_6.setText(_translate("Dialog", "Segundo Apellido"))
        self.label_10.setText(_translate("Dialog", "Rellena los siguientes campos"))
        self.label_3.setText(_translate("Dialog", "Tipo de Libro"))
        self.label_4.setText(_translate("Dialog", "ID De Libro"))
        self.pushButton_registrar_Libros.setText(_translate("Dialog", "Registrar"))
        self.comboBox_Libro.setItemText(0, _translate("Dialog", "--- Seleccione una opción"))
        self.comboBox_Libro.setItemText(1, _translate("Dialog", "Revista"))
        self.comboBox_Libro.setItemText(2, _translate("Dialog", "Libro"))
        self.comboBox_Libro.setItemText(3, _translate("Dialog", "Tesis"))
        self.comboBox_Libro.setItemText(4, _translate("Dialog", "Articulo"))
        self.label_8.setText(_translate("Dialog", "Primer Apellido"))
        self.label_5.setText(_translate("Dialog", "Fecha De Prestamo *"))
        self.label_11.setText(_translate("Dialog", "Fecha De Devolución *"))
